remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "codeblooded"

title: "Code Blooded Docs"
description: "FTC Team 12649"

plugins:
  - jekyll-include-cache

header:
  overlay_image: /images/codebloodedbanner.png
  overlay_filter: 0.5

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/code.blooded.ftc"
    - label: "FTCodeSim"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jjophoven/FTCodeSim"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BeepBot99/CodeBloodedDecodeV3"
  since: "2026"


author:
  name             : "Code Blooded"
  avatar           : "/images/codebloodedlogo.png"
  location         : "Minneapolis, MN"
  bio              : "FTC Robotics Team 12649"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/code.blooded.ftc"
    - label: "GitHub"
      icon: "images/github.png"
      url: "https://github.com/BeepBot99/CodeBloodedDecodeV3"
    - label: "FTCodeSim"
      icon: "images/github.png"
      url: "https://github.com/jjophoven/FTCodeSim"
    - label: "Season Performance"
      icon: "images/ftcscout.png"
      url: "https://ftcscout.org/teams/12649"
